services:
  product-service:
    image: ${DOCKER_REGISTRY}/product-service:${VERSION:-latest}
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev,topics,kafka
      - CONFIG_SERVER=http://${CONFIG_SERVER_HOST}:13100
      - PRODUCT_DB_HOST=${PRODUCT_DB_HOST}
      - PRODUCT_DB_PORT=${PRODUCT_DB_PORT:-5432}
      - PRODUCT_DB_NAME=${PRODUCT_DB_NAME:-p_product}
      - PRODUCT_DB_USERNAME=${PRODUCT_DB_USERNAME}
      - PRODUCT_DB_PASSWORD=${PRODUCT_DB_PASSWORD}
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS}
      - TRUST_STORE_PASSWORD=${TRUST_STORE_PASSWORD}
    volumes:
      - ./ssl:/app/ssl
    depends_on:
      - product-db

  product-db:
    image: postgres:16
    container_name: product-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${PRODUCT_DB_NAME:-p_product}
      - POSTGRES_USER=${PRODUCT_DB_USERNAME}
      - POSTGRES_PASSWORD=${PRODUCT_DB_PASSWORD}
    volumes:
      - product-db-data:/var/lib/postgresql/data
      - ./init/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  product-db-data: