spring:
  application:
    name: product-service

  config:
    import:
      - optional:configserver:${CONFIGSERVER}
      - classpath*:application-error.yml
      - classpath:application-error-product.yml
